services:
  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - api
  api:
    build:
      context: flask-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
